import { Lists } from "../../../@types/typesAndInterfaces";

export const skillSetItemList: Lists[] = [
  { content: "React", id: 1 },
  { content: "React Router", id: 2 },
  { content: "Promises, Async/Await", id: 3 },
  { content: "Typescript", id: 4 },
  { content: "Redux-Saga", id: 5 },
  { content: "GitHub Pull Requests & Review", id: 6 },
  { content: "Redux (Toolkit)", id: 7 },
  { content: "React Hooks", id: 8 },
  { content: "Trello", id: 9 },
  { content: "Git", id: 10 },
  { content: "CSS Grid", id: 11 },
  { content: "CSS Flexbox", id: 12 },
  { content: "Styled-Components", id: 13 },
  { content: "React Query", id: 14 },
  { content: "NPM", id: 15 },
  { content: "JavaScript: ES6+", id: 16 },
  { content: "Working with API (fetch, axios)", id: 17 },
  { content: "Semantic & accessible HTML", id: 18 },
  { content: "Immutability", id: 19 },
  { content: "Responsive Web Design", id: 20 },
  { content: "Error handling", id: 21 },
  { content: "React Testing Library", id: 22 },
  { content: "Jest", id: 23 },
  { content: "CSS BEM convention", id: 24 },
  { content: "Markdown", id: 25 },
  { content: "Scrum", id: 26 },
  { content: "Figma", id: 27 },
  { content: "Storybook", id: 28 },
];
